### ISSUE TITLE
防抖工具打开rtsp崩溃

### ISSUE THREAD

**Issue by lilei-John** [xiaoqinxing/ImageTools#22]
![图片](https://user-images.githubusercontent.com/21105903/224886319-e679e25c-ad9f-45f6-a426-2515053bc41a.png)
输入rtsp的用户名密码端口选择非移动设备后点击ok崩溃

**Comment by lilei-John** [comment]
method DESCRIBE failed: 404 File not found

**Comment by lilei-John** [comment]
[h264 @ 000001e2e373e900] non-existing PPS 0 referenced
[h264 @ 000001e2e373e900] non-existing PPS 0 referenced
[h264 @ 000001e2e373e900] decode_slice_header error
[h264 @ 000001e2e373e900] no frame!
[h264 @ 000001e2e373e900] non-existing PPS 0 referenced
[h264 @ 000001e2e373e900] non-existing PPS 0 referenced
[h264 @ 000001e2e373e900] decode_slice_header error
[h264 @ 000001e2e373e900] no frame!
[h264 @ 000001e2e373e900] non-existing PPS 0 referenced
[h264 @ 000001e2e373e900] non-existing PPS 0 referenced
[h264 @ 000001e2e373e900] decode_slice_header error
[h264 @ 000001e2e373e900] no frame!
[h264 @ 000001e2e3761080] non-existing PPS 0 referenced
手动修改rtsp地址后报打开视频失败，但是vlc中可以播放，视频为h264编码

**Comment by lilei-John** [comment]
打开视频文件mp4也无法播放
Traceback (most recent call last):
  File "E:\work\ImageTools-master\ImageTools-master\tools\shake_test\shake_test.py", line 133, in open_video
    self.open_video_path(videopath[0])
  File "E:\work\ImageTools-master\ImageTools-master\tools\shake_test\shake_test.py", line 137, in open_video_path
    self.vertify_video()
  File "E:\work\ImageTools-master\ImageTools-master\tools\shake_test\shake_test.py", line 221, in vertify_video
    frame = cv2.circle(self.old_gray, (a, b), 4, 255, -1)
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type

**Comment by lilei-John** [comment]
cv2.circle(new_gray, (int(a), int(b)), 8, 255, -1)强制成整形问题搞定，实时流画面出图比较慢还需要研究下
